name: Nightly Build

on:
  schedule:  # UTC at 0300 - 11pm EDT
    - cron:  '0 3 * * *'
  workflow_dispatch:

jobs:
  nightly:
    name: Nightly build
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install build requirements
        run: pip install .[test]

      - name: docker
        run: docker pull ${{ env.ENSIGHT_IMAGE }}

      - name: Run pytest
        uses: ansys/actions/tests-pytest@v4
        env:
          ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          checkout: false
          requires-xvfb: true

      - uses: codecov/codecov-action@v3
        name: 'Upload coverage to CodeCov'

      - name: Upload wheel
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v3
        with:
          name: ansys-pyensight-wheel
          path: dist/
          retention-days: 7
          if-no-files-found: error

      - name: Upload to Ansys Azure PyPi
        if: ${{ !env.ACT }}
        run: twine upload --verbose dist/*
        env:
          TWINE_USERNAME: PAT
          TWINE_PASSWORD: ${{ secrets.PYANSYS_PYPI_PRIVATE_PAT }}
          TWINE_REPOSITORY_URL: ${{ secrets.PRIVATE_PYPI_URL }}

  build-failure:
    name: Teams notify on failure
    if: failure()
    needs: [ nightly ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Microsoft Teams Notification
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: Nightly build failure
          notification-color: dc3545
          timezone: America/New_York
