name: Nightly Documentation Build

on:
  schedule:  # UTC at 0400 - 12am EDT
    - cron:  '0 4 * * *'
  workflow_dispatch:

env:
  DOCUMENTATION_CNAME: 'ensight.docs.pyansys.com'
  ENSIGHT_IMAGE: 'ghcr.io/ansys-internal/ensight_dev'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs_build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v5

      - name: Login in Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ansys-bot
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker pull
        run: docker pull ${{ env.ENSIGHT_IMAGE }}

      - name: Run Ansys documentation building action
        uses: ansys/actions/doc-build@v10
        env:
          ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
        with:
          sphinxopts: '-j auto'

  docs_upload:
    needs: docs_build
    runs-on: ubuntu-latest
    steps:

      - name: Deploy development documentation
        uses: ansys/actions/doc-deploy-dev@v10
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}

